### ISSUE TITLE
Please add documentation about the decode_kwargs

### ISSUE THREAD

**Issue by ishirav** [yjmade/django-pgjsonb#11]
The default behavior of converting floats to Decimals is somewhat surprising, and there's no documentation about it or how to change it. Thanks

**Comment by yjmade** [comment]
This piece of code come from django-postgres , but they actually didn't make the decode_kwargs to work. As version 0.0.18 I fix it to let itreally do the job, then what is left from  django-postgres get effect. I don't expect this behavior either. So maybe I can remove this default behavior and add it to document, what do you think.

**Comment by ishirav** [comment]
There are two separate issues:
1. Deciding what is the default behavior - floats or Decimals? 
2. Documenting the decode_kwargs and how to change the default if you need to.

Before 0.0.18 the default was floats, and now it changed to Decimals. Whether you want to revert it back to floats is up to you.

But no matter what you decide, some documentation is needed :)

**Comment by yjmade** [comment]
before 0.0.18 is float is because the decode_kwargs is not working at all.
anyway, I'm gonna remove this Decimal-float and add some documents
