### ISSUE TITLE
add postgresql earthdistance support to jsonfield

### ISSUE THREAD

**Issue by steinliber** [yjmade/django-pgjsonb#13]
Hi, thanks for your awesome tool, I recently want to add geo support for my app using the jsonb field, but pgjsonb doesn't support this now, so i can raise a PR for that, What do you think about this

**Comment by yjmade** [comment]
nice, it will very good to have that. Please do

**Comment by steinliber** [comment]
Can you please update this new feature to pypi, so everyone can use this easily

**Comment by steinliber** [comment]
@yjmade

**Comment by yjmade** [comment]
👌,will do
