### ISSUE TITLE
关于测试中删除索引导致无法正常运行的问题

### ISSUE THREAD

**Issue by steinliber** [yjmade/django-pgjsonb#15]
在 django 运行测试时，因为数据库有可能会重新建，而删除旧的索引导致数据库异常，导致无法正常运行测试。
在源代码中，删除索引没有处理可能发生的异常
`
for index_name in to_delete_indexes:
    editor.execute(editor._delete_constraint_sql(editor.sql_delete_index, model, index_name))
`
我的想法是捕捉到对应的异常，给予相关有用的提醒。

**Comment by yjmade** [comment]
#16
