### ISSUE TITLE
请问可以checkout 一个版本自己公司内部使用吗

### ISSUE THREAD

**Issue by steinliber** [yjmade/django-pgjsonb#21]
Hello，非常感谢你写的库，给我们开发省了很多时间，但好像没有看到这个项目的开源证书，我们公司想增加一些特定的查询，请问可以checkout 一个分支出来让我们自己使用吗

**Comment by yjmade** [comment]
可以的,没有问题. 还是希望有可能的话可以把扩充的功能通过PR回馈过来

**Comment by steinliber** [comment]
ok,谢了
