### ISSUE TITLE
select_json does not assign field name properly

### ISSUE THREAD

**Issue by tjratch** [yjmade/django-pgjsonb#9]
Hi There,

I tried assigning a field name company_id using the select_json paths functionality demoed at the bottom of the documentation as follows:

![image](https://cloud.githubusercontent.com/assets/14169397/13619480/55e2d690-e557-11e5-87eb-a9550c8a7625.png)

However, it doesn't seem to work and I get the following error:

```
    count=models.Count("company_id"))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 802, in annotate
    is_summary=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1053, in add_aggregate
    field_list, opts, self.get_initial_alias())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1463, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1427, in names_to_path
    self.raise_field_error(opts, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1433, in raise_field_error
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'company_id' into field. Choices are: created, data, id
```

Any ideas? Please advise.

**Comment by yjmade** [comment]
I'm assuming that company_id is an array and you want to get the length of it.
you can not annotate by models.Count to get the array length for the jsonb field, because it's for the foreignkey style of relation counting. 
I have add a new feature in the 0.0.20 version that you can simply 

``` python
Event.objects.all().select_json(Length("data__company_id")).values("company_id_len")
```

**Comment by tjratch** [comment]
Hi There,

Firstly, thank you very much for making this library and supporting it!

My mistake, I should have been more specific in my question. I'm basically trying to group by company_id and get a count. My JSON objects look like this:

```
{
   "type" : "banana",
   "company_id": "1337"
}
```

So in SQL I would do:

```
select
    distinct data ->> 'company_id',
    count(*)
  from event_log
  where data ->> 'type' = 'banana'
  group by data ->> 'company_id'
```

So I was trying to use django-jsonb to perform the same query as follows

```
Event.objects.filter(data__contains={"type":"banana"}).select_json(company_id="data__company_id").values("company_id").annotate(count=models.Count("company_id"))
```

**Comment by yjmade** [comment]
Event.objects.select_json("data__type").values("type").annotate(ct=models.Count("pk"))

**Comment by tjratch** [comment]
Thank you so much! That did it!
